######################################################################
# Automatically generated by qmake (2.01a) Mi. Dez 30 15:20:21 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
